name: Publish

on: 
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
    secrets:
      HEX_API_KEY:
        required: true

jobs:
  publish:
    env:
      MIX_ENV: docs
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14
          otp-version: 25.x

      - name: Restore dependencies cache
        uses: actions/cache@v3
        id: cache-elixir-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Install Dependencies
        if: steps.cache-elixir-deps.outputs.cache-hit != 'true'
        run: mix do deps.get, deps.compile, compile

      - name: Build and publish docs
        if: inputs.mode == 'docs'
        run: mix hex.publish docs --yes

      - name: Build and publish package
        if: inputs.mode == 'package'
        run: mix hex.publish --yes
