name: Retire

on: 
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      version:
        required: true
        type: string
      reason:
        required: true
        type: string
      message:
        required: true
        type: string
        
    secrets:
      HEX_API_KEY:
        required: true

jobs:
  retire:
    env:
      MIX_ENV: docs
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: 27.x

      - name: Retire the package version
        run: mix hex.retire ${{ inputs.package }} ${{ inputs.version }} ${{ inputs.reason }} --message "${{ inputs.message }}"
